<?php

namespace AppBundle\Repository;

/**
 * EngagementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EngagementRepository extends \Doctrine\ORM\EntityRepository
{
}
