<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * InvoiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends EntityRepository
{
    public function findByYear($year)
    {
        $em = $this->getEntityManager();

        $startDate = new \DateTimeImmutable("$year-01-01T00:00:00");
        $endDate = new \DateTimeImmutable("$year-12-31T23:59:59");

        $query = $em->createQuery(
            'SELECT i
             FROM AppBundle:Invoice i'
//             WHERE i.createdAt
//             BETWEEN :start AND :end'
//        )->setParameters(array(
//            'start' => $startDate->format('‌​Y-m-d H:i:s'),
//            'end' => $endDate->format('‌​Y-m-d H:i:s'),
//        ));
        );

        return $query->getResult();
    }
}
