<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $slug
     * @return mixed
     */
    public function findOneRepairDeviceByCode ($code)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT r
             FROM AppBundle:Receipt r
             WHERE r.code = :slug'
        )->setParameters(array(
            'slug' => $code
        ));

        return $query->getOneOrNullResult();
    }
}
