<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ReceiptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReceiptRepository extends EntityRepository
{
    /**
     * @param $slug
     * @return mixed
     */
    public function findOneByCode ($code)
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery(
            'SELECT r
             FROM AppBundle:Receipt r
             WHERE r.code = :code'
        )->setParameters(array(
            'code' => $code,
        ));

        return $query->getOneOrNullResult();
    }
}
